sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.6

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "yoon9660@gmail.com"
  - git config --global user.name "Yoon Gun-hee"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "O9YekNN2RiI60tbTAN474Xm8kg30nfiErY0mjrNHzOFxZ9sXdKYn+6Vvefh3Mw8Skw2KK3JKvS7mDHV1syyWqcsUzbFGTItC5PPvF41WaKxaiQGsrtaY+uTAvK5QPwnbwUW9RGD3zXAq4VGdBjCq4Q6fADdUBEn8O88OGswMzEccvEpEcD+KVXb19MQjBBcSAzggwp5bBTyqRARcgsVovRXHVOaGkXIj
09MduiAyWxT0p1tKo8eSnJeXBZ8591s3lzudY0gYbg+G1MdNQ6lG4P0zmeUAZOV2BsO9a570vzc8SDZzp6ousr2pdz0plXvpX2q9UW8R6gn2r5ZA2kBlDiyUhUMvpJJyi6818j+Bb6yDiE/qCRuDAZ38t7tcLJHKMEoPCqccehEoS7Whap0ZKfoum27L5uk3d/huJy8wdg2Ot9NtPZBte66Wm1zuls/UnQGrJPmxDOG
HwJCz9nj9hKRJV3mlqlELpPPqUwH2IXjmeSsCn/2VpaTxitbcTSpCJ4NZJ3JFNvq5vJTTOPQY6f4t/OZOIidSZfOhG+fzeK7fvuCOE6Ibzdvo1F5ScGAl6jgVCNGbFFY6/MhWhRILZeCmMSNdhWxvIVab0DEDcPGpycQYbT4lyv3rHD2qM7PENR3W7iX/Ag8DZLWg6wAM4Tgqh5dN0hiXunO6f7xmnGc="
branches:
  only:
    - master